services:
  - type: web
    name: barbershop-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_GEMINI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 